--Clientes
INSERT INTO CLI_CLIENTES(NV_NOMBRE,NV_DIRECCION,NV_CIUDAD,IN_TELEFONO) VALUES('Edwin Cardona', 'cll 10 # 10-10', 'Medellin', 5551010);
INSERT INTO CLI_CLIENTES(NV_NOMBRE,NV_DIRECCION,NV_CIUDAD,IN_TELEFONO) VALUES('Fernando Valencia', 'cll 50 # 20-20', 'Bogota', 6661010);

--Tarjetas
INSERT INTO CLI_TARJETAS(NV_NUMERO,IN_CCV,NV_TIPO,IN_CODIGO_CLIENTE) VALUES('1234 5678 9123 4567', 123, 'debito', (SELECT IN_CODIGO FROM CLI_CLIENTES WHERE NV_NOMBRE = 'Edwin Cardona'));